# Data Science Numpy & CSV's

## Tasks Today:

1) <b>Numpy</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Python List Comparison <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) In-Class Exercise #1 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Importing <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Creating an NDArray <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.array() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.zeros() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.ones() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - np.arange() <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Making Lists into NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; e) Performing Calculations on NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Summation <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Difference <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Multiplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Division <br>
 &nbsp;&nbsp;&nbsp;&nbsp; f) Numpy Subsetting <br>
 &nbsp;&nbsp;&nbsp;&nbsp; g) Multi-dimensional Arrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; h) Indexing NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; i) Checking NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; j) Altering NDArray Type <br>
 &nbsp;&nbsp;&nbsp;&nbsp; k) Checking the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; l) Altering the Shape <br>
 &nbsp;&nbsp;&nbsp;&nbsp; m) In-Class Exercise #2 <br>
 &nbsp;&nbsp;&nbsp;&nbsp; n) Complex Indexing & Assigning <br>
 &nbsp;&nbsp;&nbsp;&nbsp; o) Elementwise Multplication <br>
 &nbsp;&nbsp;&nbsp;&nbsp; p) np.where() <br>
 &nbsp;&nbsp;&nbsp;&nbsp; q) Random Sampling <br>

2) <b>Working With CSV's</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) Imports <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) Reading a CSV <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) Loading a CSV's Data <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) Checking Number of Records <br>
 
3) <b>Exercises</b> <br>
 &nbsp;&nbsp;&nbsp;&nbsp; a) #1 - Calculate BMI with NDArrays <br>
 &nbsp;&nbsp;&nbsp;&nbsp; b) #2 - Find the Average Sum of Marathon Runners <br>
 &nbsp;&nbsp;&nbsp;&nbsp; c) #3 - Random Matrix Function <br>
 &nbsp;&nbsp;&nbsp;&nbsp; d) #4 - Comparing Boston Red Sox Hitting Numbers <br>

## Numpy <br>

<p>NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.</p>
<ul>
    <li>Shape = Rows & Columns</li>
    <li>Matrix = Entire Array</li>
    <li>Vector = Variables to be applied (same vector as the one used in physics)</li>
    <li>Array = Similar to lists</li>
</ul>

#### Python List Comparison

<p>Lists are flexible, dynamic python objects that do their job quite well. But they do not support some mathematical operations in an intuitive way. Consider the summation of two lists, $l_1$ and $l_2$</p>

In [1]:
# create two lists and sum both of them together (results may not be what you expect)
l_1 = [1,2,3]
l_2 = [4,5,6]

print(l_1 + l_2)

[1, 2, 3, 4, 5, 6]


<p>If we wanted to sum lists elementwise, we could write our own function that does the job entirely within the framework of python</p>

#### In-Class Exercise #1 - Write a function that sums the indexes of two lists <br>
<p>Ex: [2, 3, 4] + [1, 5, 2] = [3, 8, 6]</p>

In [5]:
def sumindy(l1,l2):
    new = []
    for i in range (len(l1)):
        a = l1[i] + l2[i]
        new.append(a)
    return new
        
sumindy([2,3,4],[1,5,2])


[3, 8, 6]

#### Importing

In [3]:
# always import as np, standard across all of data science
import numpy as np

#### Creating an NDArray <br>
<p>NumPy is based around a class called the $\textit{NDArray}$, which is a flexible vector / matrix class that implements the intuitive matrix and vector arithmatic lacking in basic Python. Let's start by creating some NDArrays:</p>

###### - np.array()

In [6]:
arr1 = np.array([1,2,3])
arr1

array([1, 2, 3])

###### - np.zeros()

In [13]:
# Shape -- np.zeros() has a parameter of "shape" that must be given
arr_zeros = np.zeros((3,3))
arr_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

###### - np.ones()

In [11]:
arr_ones = np.ones((3,3),int)
arr_ones

# notice no dots after the numbers, because we specified the datatype to be integer

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

###### - np.arange()

In [16]:
arr_range = np.arange(1,12)
arr_range

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

###### - Making Lists into NDArrays

In [17]:
l1 = [4,5,6]

arr_list = np.array(l_1)
arr_list

array([1, 2, 3])

#### Performing Calculations on NDArrays

###### - Summation

In [18]:
arr_list1 = np.array([5,10,15,20,25])

arr_list2 = np.array([10,20,30,40,50])

result_sum = arr_list1 + arr_list2
result_sum

array([15, 30, 45, 60, 75])

###### - Difference

In [22]:
result_diff = abs(arr_list1 - arr_list2)
result_diff

array([ 5, 10, 15, 20, 25])

###### - Multiplication

In [23]:
result_mul = arr_list1 * arr_list2
result_mul

array([  50,  200,  450,  800, 1250])

###### - Division

In [24]:
result_diff = arr_list2 / arr_list1
result_diff

array([2., 2., 2., 2., 2.])

In [25]:
# Modulo
result_mod = arr_list2 / arr_list1
result_diff

array([2., 2., 2., 2., 2.])

In [26]:
# Floor Division
result_floor = arr_list2 // arr_list1
result_floor

array([2, 2, 2, 2, 2], dtype=int32)

#### Numpy Subsetting

In [28]:
# result3 <= 800
print(result_mul <= 800)
print(result_mul[result_mul <= 800])

# conditioal check, returns true or false
# print(arr1 < 2)
# print(arr2 >= 2)

# conditional check, that returns the elements that meet the given condition


[ True  True  True  True False]
[ 50 200 450 800]


#### Multi-dimensional Arrays <br>
<p>NumPy seamlessly supports multidimensional arrays and matrices of arbitrary dimension without nesting NDArrays. NDArrays themselves are flexible and extensible and may be defined with such dimensions, with a rich API of common functions to facilitate their use. Let's start by building a two dimensional 3x3 matrix by conversion from a nested group of core python lists $M = [l_0, l_1, l_2]$:</p>

In [33]:
aList = [0,1,2]
bList = [3,4,5]
cList = [6,7,8]

# first step : Convert the Lists into a Matrix =>
M = [aList,bList,cList]
print(M)

# second step: place Matrix inside NDArray
ND_M = np.array(M)
print(ND_M)

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Indexing NDArrays <br>
<p> Similar to lists within lists; however, the syntax looks more like C programming language.... It is [1, 2] to access the second row, third element.</p>

In [34]:
print(f'Getting the Middle element within the Matrix: {ND_M[1,1]}')

Getting the Middle element within the Matrix: 4


#### Assigning Values in NDArrays

In [42]:
  # trying to change to floating point number
ND_M[1,1] = 3 ** 2
ND_M

array([[0, 1, 2],
       [3, 9, 5],
       [6, 7, 8]])

<p>Notice above how we ended up with a 1 in the target element's place. This is a data type issue. The .dtype() method is supported by all NDArrays, as well as the .astype() method for casting between data types:</p>

#### Checking NDArray Type

In [43]:
#using the .dtype()method
nd_type = ND_M.dtype
nd_type

dtype('int32')

#### Altering NDArray Type

In [46]:
result_type = nd_type
print(f'Type before Change: {result_type}')

# Change Happens Here : 
changed = ND_M.astype(np.float64)

result_changed = changed

print(f'Type after change: {result_changed.dtype} ')
print(changed)

Type before Change: int32
Type after change: float64 
[[0. 1. 2.]
 [3. 9. 5.]
 [6. 7. 8.]]


#### Checking the Shape <br>
<p>The behavior and properties of an NDArray are often sensitively dependent on the $\textit{shape}$ of the NDArray itself. The shape of an array can be found by calling the .shape method, which will return a tuple containing the array's dimensions:</p>

In [49]:
 # shape is always rows x column
l = changed.shape
print(l)

(3, 3)


#### Altering the Shape <br>
<p>As long as the number of elements remains fixed, we can reshape NDArrays at will:</p>

In [50]:
# Change the shape of the numpy array
# Using the method .reshape()

# The reshape should be a multiple of the original shape
# Meaning we can have a shape of (1,9) or (9,1) or (3,3)

# (9,1) == 9 rows , 1 column

print(ND_M.reshape((9,1)))

[[0]
 [1]
 [2]
 [3]
 [9]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
# keep in mind that the shape numbers do matter, (9, 1) is different than (1, 9)


#### In-Class Exercise #2 - Create a matrix of range 0 up to 16 and reshape it into a 4x4 matrice

In [ ]:
# arr1 = np.array([0,16])
# new_array = np.arr1([4,4])
# print(type(test.shape))



#### Complex Indexing & Assinging

In [52]:
M_zeros = np.zeros((6,6))
print('Reseting Matrix')
print ('Before Assignment')
print (M_zeros)


#set every first element in each row to 1
M_zeros[:,0] = 1
print('\n After Assigning 1 to First Column:')
print(M_zeros)

# Set every element in the axis of 3 to 5 (Excluding 5) to be equal to 5
M_zeros [2:5, :1] = 5
print('\n After Assigning 5 to rows 3-5 (not including 5):')
print(M_zeros)

Reseting Matrix
Before Assignment
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

 After Assigning 1 to First Column:
[[1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0.]]


#### Elementwise Multiplication

<p>As long as the shapes of NDArrays are 'compatible', they can be multiplied elementwise, broadcasted, used in inner products, and much much more. 'Compatible' in this context can mean compatible in the linear algebraic sense, i.e. for inner products and other matrix multiplication, or simply sharing a dimension in such a manner that broadcasting 'makes sense'. Here are some examples of this:</p>

In [53]:
# Initialize a vector of range 6, reset to Zero

v = ND_M[:,:] = 0

# Reset our Matrix back to zero
M_zeros = M_zeros * 0

# Change V to hold numbers from 1 - 6 reshaped to (6,1)

v = np.arange(6).reshape(6,1)

# print for correctness
print(M_zeros)
print(v)

#Vector multiplication happens here



[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


#### np.where() <br>
<p>If statement within NDArrays that allows you to run conditionals on the entire array</p>

In [54]:
all_under_value = result_mul[np.where(result_mul <= 800)]
print(all_under_value)

[ 50 200 450 800]


#### Random Sampling <br>
<p>NumPy provides machinery to work with random numbers - something often needed in a broad spectrum of data science applications.</p>

In [55]:
# np.random.uniform()

# A single call generates a single random number between 0 and 1

print('Here is a random number: %s' % np.random.uniform())

# You can also pass some parameters or bounds

print('Here is a random number between 0 and 1 Million: %s' % np.random.uniform(0, 1e6))

# You can also generate a bunch of random numbers all at once

print('Here are 5 random numbers between 0 and 10: %s' % np.random.uniform(0, 10, 5))

# Even matrices with shapes as a parameter

print('Here is a 3x3 matrix with numbers between 0 and 10: \n %s' % np.random.uniform(0, 10, (3, 3)))

Here is a random number: 0.3391493656272815
Here is a random number between 0 and 1 Million: 454083.357338218
Here are 5 random numbers between 0 and 10: [5.73004931 8.62163271 6.67681104 3.65787643 2.87485073]
Here is a 3x3 matrix with numbers between 0 and 10: 
 [[8.8938584  8.37338687 9.29274006]
 [9.44597934 4.43798937 0.26193208]
 [4.09408949 6.80356812 0.97722089]]


## Working With CSV's

#### Imports

In [56]:
import csv
import numpy as np
from datetime import datetime

#### Reading a CSV

In [63]:
# Creating a Function to open and read CSV Data

def open_csv(filename, d = ','):
    # define an empty list to store our data
    data = []
    
    # Open our data file and read the contents inside
    with open(filename, encoding = 'utf-8') as mData:
        #use the csv.reader method to create a python list
        info = csv.reader(mData, delimiter = d)
        
        #Loop over info and append data
        for row in info:
            data.append(row)
    return data
csv_data = open_csv('../files/boston_marathon2017_edited.csv')

print(csv_data[2])

['12/30/1899 12:30:27 AM', '12/30/1899 12:45:44 AM', '12/30/1899 1:01:15 AM', '12/30/1899 1:16:59 AM', '12/30/1899 1:33:01 AM', '12/30/1899 1:48:19 AM', '12/30/1899 2:03:14 AM', '12/30/1899 12:15:24 AM', '30', '17', '7798', 'USA', '7798', '', 'Portland', 'USA', '2', '2', '12/30/1899 1:04:35 AM', 'M', 'Rupp, Galen', '1', '12/30/1899 2:09:58 AM', '2', '12/30/1899 12:04:58 AM', 'OR']


#### Loading a CSV's Data 

In [66]:
FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]



    # instead of loading csv normally, let's load it into a numpy array to calculate results on
def load_data(filename, d = ','):
    data = np.genfromtxt(filename, delimiter = d, skip_header = 1,
                        usecols = np.arange(0,24), invalid_raise = False,
                        names = FIELDS, dtype = DATATYPES)imsi

    return data

bs2017 = load_data('../files/redsox_2017_hitting.txt')
print(bs2017)


[( 1, b'C', b'Christian Vazquez', 26,  99, 345, 324,  43,  94, 18, 2,  5,  32,  7, 2, 17,  64, 0.29 , 0.33 , 0.404, 0.735,  91, 131, 14)
 ( 2, b'1B', b'Mitch Moreland', 31, 149, 576, 508,  73, 125, 34, 0, 22,  79,  0, 1, 57, 120, 0.246, 0.326, 0.443, 0.769,  99, 225, 14)
 ( 3, b'2B', b'Dustin Pedroia', 33, 105, 463, 406,  46, 119, 19, 0,  7,  62,  4, 3, 49,  48, 0.293, 0.369, 0.392, 0.76 , 100, 159, 11)
 ( 4, b'SS', b'Xander Bogaerts', 24, 148, 635, 571,  94, 156, 32, 6, 10,  62, 15, 1, 56, 116, 0.273, 0.343, 0.403, 0.746,  95, 230, 17)
 ( 5, b'3B', b'Rafael Devers', 20,  58, 240, 222,  34,  63, 14, 0, 10,  30,  3, 1, 18,  57, 0.284, 0.338, 0.482, 0.819, 111, 107,  5)
 ( 6, b'LF', b'Andrew Benintendi', 22, 151, 658, 573,  84, 155, 26, 1, 20,  90, 20, 5, 70, 112, 0.271, 0.352, 0.424, 0.776, 102, 243, 16)
 ( 7, b'CF', b'Jackie Bradley Jr.', 27, 133, 541, 482,  58, 118, 19, 3, 17,  63,  8, 3, 48, 124, 0.245, 0.323, 0.402, 0.726,  89, 194,  8)
 ( 8, b'RF', b'Mookie Betts', 24, 153, 712, 62

#### Summing the top 5 hitters for HR's

In [74]:
# find the top 5 hr hitters

# Step 1: Get all HR Data into a variable
all_hr = bs2017['HR']

#Step 2: Get all Player Names
all_names = bs2017['Name']

#Step 3: Create new list for new_names (empty to start)
new_names = []

#Step 4: Decode the player names into regular strings
for name in range(len(all_names)):
    new_names.append(all_names[name].decode('utf-8'))

# print(new_names)    
    #Step 5: Grab all Data and place inside of a zipped list
zipped_values = list(zip(new_names,all_hr))
# print(zipped_values)



#Step 6: Sort values based on HR data
sorted_hr = sorted(zipped_values, key = lambda x: x[1], reverse = True)

print(sorted_hr)

# print(hr)


[('Mookie Betts', 24), ('Hanley Ramirez', 23), ('Mitch Moreland', 22), ('Andrew Benintendi', 20), ('Jackie Bradley Jr.', 17), ('Xander Bogaerts', 10), ('Rafael Devers', 10), ('Eduardo Nunez', 8), ('Dustin Pedroia', 7), ('Sandy Leon', 7), ('Chris Young', 7), ('Christian Vazquez', 5), ('Deven Marrero', 4), ('Pablo Sandoval', 4), ('Brock Holt', 0), ('Josh Rutledge', 0), ('Sam Travis', 0), ('Tzu-Wei Lin', 0), ('Marco Hernandez', 0), ('Rajai Davis', 0), ('Steve Selsky', 0), ('Blake Swihart', 0), ("Chase d'Arnaud", 0)]


# Exercises To Complete.... <br>
<p>Given in separate file after completion of this file</p>

#homework is similiar to loadcsv and summing data